cache: bundler
sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
# these haven't been passing for a while:
#  - jruby-head
#  - rbx

gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0_foreigner.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_edge.gemfile

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script: WITH_ADVISORY_LOCK_PREFIX=$TRAVIS_JOB_ID bundle exec rake --trace spec:all

matrix:
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: jruby-head
    - rvm: rbx
